# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "space_vim_theme"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_vimfiler_filetypeicon = true
    relativenumber = false
    default_indent = 4
    expand_tab = true
    filemanager = "defx"
    autocomplete_method = "coc"
    lint_engine = "ale"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    enable_statusline_mode = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    enable_statusline_bfpath = true

[[custom_plugins]]
repo = "mrjones2014/space-vim-theme"
merged = 0

[[custom_plugins]]
repo = "sheerun/vim-polyglot"
merged = 0

[[custom_plugins]]
repo = "tpope/vim-sleuth"
merged = 0

[[custom_plugins]]
repo = "tpope/vim-commentary"
merged = 0

[[custom_plugins]]
repo = "APZelos/blamer.nvim"
merged = 0

[[custom_plugins]]
repo = "blueyed/vim-diminactive"
merged = 0

[[layers]]
name = "ui"
enable_scrollbar = true
enable_indentline = true

[[layers]]
name = "lsp"
filetypes = [
    "javascript",
    "typescript"
]
    [layers.override_cmd]
    typescript = ['typescript-language-server', '--stdio']
    javascript = ['typescript-language-server', '--stdio']

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "core"
filetree_show_hidden = true

[[layers]]
name = "format"
enable = false
format_on_save = true

[[layers]]
name = "checkers"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"
git-plugin="fugitive"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#html"
format_on_save = false

[[layers]]
name = "lang#markdown"
format_on_save = false

[[layers]]
name = "lang#sh"

[[layers]]
name = "fzf"

