#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "tokyonight"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = false
    default_indent = 4
    expand_tab = true
    filemanager = "defx"
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[custom_plugins]]
repo = "ghifarit53/tokyonight-vim"
merged = 0

[[custom_plugins]]
repo = "sheerun/vim-polyglot"
merged = 0

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "core"
filetree_show_hidden = true

[[layers]]
name = "format"
format_on_save = true

[[layers]]
name = "checkers"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#html"
format_on_save = false

[[layers]]
name = "lang#markdown"
format_on_save = false

[[layers]]
name = "lang#sh"

[[layers]]
name = "fzf"

