docs: docs/
readme: README.md
fish: .config/fish/
tmux: .config/tmux/tmux.conf
scripts: scripts/
kitty: .config/kitty/
hammerspoon: .config/hammerspoon/
vim: .config/nvim/
paths: .config/config-paths.yml
ignore: .config/.ignore
codespell: .config/codespell/custom_dict.txt
ssh: .ssh/config
wezterm: .config/wezterm/
cbfmt: .config/cbfmt.toml
home: .config/home-manager/
nix: .config/nix/nix.conf
git: .config/home-manager/modules/git.nix
bat: .config/home-manager/modules/bat.nix
starship: .config/home-manager/modules/starship.nix
atuin: .config/home-manager/modules/atuin.nix
topgrade: .config/home-manager/modules/topgrade.nix
