fish: .config/fish/
tmux: .config/tmux/
scripts: scripts/
kitty: .config/kitty/
alacritty: .config/alacritty/
hammerspoon: .hammerspoon/
vim: .config/nvim/
git: .config/git/
bat: .config/bat/config
starship: .config/starship.toml
paths: .config/config-paths.yml
ignore: .config/.ignore
vale: .config/vale/
