format = """
 $directory$git_branch$git_status
 $character """

[character] # colors from ~/.config/kitty/lighthaus-theme.conf
success_symbol = "[ ](bold #00BFA4)"
error_symbol = "[ ](bold #FF5050)"
vicmd_symbol = "[ ](bold #44B273)"

[git_branch]
symbol = " "
style = "bold #f74e27" # git brand color

[directory]
read_only = " "
