format = """
 $directory$git_branch$git_status$git_state
 $character """

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[git_branch]
symbol = " "
style = "bold #f74e27"

[directory]
read_only = " "
